### ISSUE TITLE
YouPHPTube (((New Appliance))

### ISSUE THREAD

**Issue by MPTMG** [turnkeylinux/tracker#1027]
This appliance is about 95% complete. Code not posted yet, but soon. I will need a bit of help on this one if there is someone in the community with the requisite knowledge. Only thing left to do is script the initial setup. I reviewed some of the other similar appliances (wordpress, e107), but I am not experienced with using curl in cons.d/main to configure the appliance.

**Comment by JedMeister** [comment]
You my friend are a bloody legend! Another great looking appliance! You must be getting sick of my apologies about how long things are taking...

We're super close to a v15.0RC Core release, the thing that's currently blocking is getting our pacakge to build reproducibly in our package building infrastructure.

WRT to using a curl install, TBH, it's been ages since I've done a new one. 

IIRC I used to use Firefox with the [LiveHTTPHeaders](http://livehttpheaders.mozdev.org/) addon. You then go through the in browser installation as per usual and watch the traffic via the addon. You can then replay it via curl commands.

I also just asked one of our devs and he said that it's been a little while since he's done a new one too but said that the network tab in Firefox developer tools should probably be enough these days. 

Chrome has something similar, although I do recall that wasn't as good as LiveHTTPHeaders.

Have a bit of a play and see how you go. I don't want to pull any of the devs off v15.0 work ATM, but if things go to plan over the next few weeks (as they do on the odd occasion...) then perhaps one of them may be able to give you a hand?

**Comment by MPTMG** [comment]
I will give LiveHTTPHeaders a go and try to do the replay via curl. Wasn't asking for anyone to come off v15.0 as I am anxiously awaiting it also to ensure I make the requisite changes to the appliances I have already submitted for the transition to stretch. Thanks for the heads up on LiveHTTPHeaders.

**Comment by MPTMG** [comment]
Have not forgotten about this one. Everything is complete to the point where final config files need to be written. I have come up at a loss using LiveHTTPHeaders, but it looks like I can use the database creation script, write the config file via conf.d, and script the admin user creation in the database.

Do not have a good ETA when I will be done right now. Will report back as I make progress.

**Comment by JedMeister** [comment]
> I have come up at a loss using LiveHTTPHeaders

Hmm, that sucks.

> I can use the database creation script, write the config file via conf.d, and script the admin user creation in the database.

A DB creation script within the YouPHPTube code you mean? Or something else? 

If you can leverage something within the code (within a `conf.d` script) that is easy to read, then go for it. Please don't include SQL dumps though. They're notoriously hard to read and maintain.

Adding config file via `conf.d` script (or even overlay) and scripting admin user creation is fine. :smile:

**Comment by MPTMG** [comment]
The code for YouPHPTube includes a database generation script it is not a dump.

Link to database creation script in YouPHPTube code for reference.
https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/install/database.sql

I will not use any dumps. Following the php in the install it basically does 3 things during install. It executes the database.sql, creates a config file in /var/www/html/$YouPHPTubeDirectory/videos and adds the admin user and email to the database.

I think I can accomplish this relatively easily by scripting database creation into conf.d, creation of admin user in conf.d, and writing the config file in conf.d or including in overlay.

Essentially leaving three inithooks for final config. First init would require user to enter web address for the youphptube server and update youphptube config file. Second hook would update the database password for youphptube database user and update config file to match, third would update the admin user's password in database.

Since YouPHPTube is a two part app this would happen essentially twice once for the YouPHPTube site and once for the YouPHPTube encoder site. Both will be installed and configured by default.

https://github.com/DanielnetoDotCom/YouPHPTube
https://github.com/DanielnetoDotCom/YouPHPTube-Encoder

**Comment by MPTMG** [comment]
This one is 100% functional and ready to go. Is there a how to on the README file? I don't know if it is my text editor or something, but I lose the links and pickup weird syntax in the README when trying to use other appliances as a template. Ready for you or some other person in charge of screening the code to take a look and comment. Will add art tomorrow (my least favorite part of the whole process).

I decided to move the encoder to a second appliance (work started as it mirrors work in this appliance), but after some discussion with a peer the encoder would be better served in a secondary appliance in order to avoid having encoding cause performance degradation on front-end delivery of video. A public encoder provided by YouPHPTube developer is configured by default.

**Comment by JedMeister** [comment]
Ok, having a look at this one next. TBH, I'm not sure how far I'll get as I really need to switch focus back to finalising updates for the current appliances. 

I really wanted to make sure that we had some progress on a couple of the apps you've contributed though. You've been doing such an awesome job and putting forward some incredible appliance candidates that I really wanted to give your appliances a bit of attention! :smile: 

Re the README file, AFAIK, no there isn't really any "how to" for those (although there probably should be...).

Essentially they are just a rst ([ReStructuredText](https://en.wikipedia.org/wiki/ReStructuredText)) file. They are plain text files and best edited with a plain text editor with a monospace font. FWIW, personally I'm a vim user so I edit them directly in my TKLDev instance. If you want to give that a go, a big tip: install vim proper (TKL only preinstalls `vim-tiny`), i.e. `apt-get install vim`. Alternatively, `nano` is also pre-installed on TKL and is probably a more initiative text editor for a non-vim user.

The beauty of rst is that it's easy to read as a plain text file (e.g. via cat from the commandline), but also really easy to render as pretty html (e.g. how GitHub displays them). We process them to produce each appliances' "appliance page" on the website.

A few formatting tips that you may or may not have noticed:

Lines should generally be no more than 80 characters (that generally applies to all code as well as readmes, but isn't really strict on appliance code and some exceptions are made when it makes sense).

Headings are underlined with `=`, subheadings with `-`. The number of underlining characters, should exactly match the number of characters of the heading/subheading (including formatting such as `*`). Hence why editing with a non-plain text editor / non-monospaced font sucks!

Links are denoted by a trailing `_`, if the link is multiple words, the words need to be wrapped in backticks ``` (that's 3; not sure how to show a single backtick in GitHub markdown?!) ; still with a trailing `_`.

E.g. `Link_` and/or \`another link`_ 

Where the link points to is done at the bottom of the file, each on it's own line that starts with `.. _`, backticks not required for multiple words.

E.g.:
```
.. _Link: https://www.somesite.com
.. _another link: https://www.othersite.com
```

Text in italics is via wrapping in single `*`, e.g. `*this is rendered in italics*`. Bold is wrapped in double `*`, e.g. `**this is rendered in bold**`.

As for the actual content, exactly what is required will differ depending on the appliance, how it's installed and what additional config has been done. So I can't really be too prescriptive. However, the current appliances are generally a decent guide. I try to keep them relatively consistent, although there are a few that have strayed, and some that are incomplete (e.g. security note about manual upgrades missing). I hope to tidy all  that for v15.0, but we'll see how we go...

As an example, this is not necessarily what all of them would need, but here's one for "SoftwareName", showing the above formatting and some of the text convention for a PHP style app install:
```
SoftwareName - Software byline (from website)
=============================================

SoftwareName_ blurb about software, usually copy.pasted straight from the software
itself...

This appliance includes all the standard features in `TurnKey Core`_,
and on top of that:

- SoftwareName configurations:
  
  - Installed from upstream source code to /var/www/softwarename.

    **Security note**: Updates to softwarename may require supervision so
    they **ARE NOT** configured to install automatically. See `softwarename
    documentation`_ for upgrading.

- SSL support out of the box.
- `Adminer`_ administration frontend for MySQL (listening on port
  12322 - uses SSL).
- Postfix MTA (bound to localhost) to allow sending of email (e.g.,
  password recovery).
- Webmin modules for configuring Apache2, PHP, MySQL and Postfix.

Credentials *(passwords set at first boot)*
-------------------------------------------

-  Webmin, SSH, MySQL: username **root**
-  Adminer: username **adminer**
-  SoftwareName: username **admin**

.. _SoftwareName: https://link.to.softwarename.website/
.. _TurnKey Core: https://www.turnkeylinux.org/core
.. _softwarename documentation: https://link.to.softwarename.website/docs/upgrading
```
I hope that helps, please ask if you have further questions.

**Comment by MPTMG** [comment]
Don't make any changes yet go to tvheadend first. I am migrating this to nginx from repo with rtmp module from repo.

**Comment by MPTMG** [comment]
I am actually building the iso right now to test before committing changes using nginx rtmp module from backports. It is 100% functional as is, but you told me do what I can to get it from nginx from repo instead.

**Comment by JedMeister** [comment]
Ok no worries. I have already built, but I will delete that one and look out for a PR from you on this one first...

**Comment by JedMeister** [comment]
Actually, FWIW, I had already tweaked the README of this one a little (as tidying up some other readmes, so did this while I was at it). I'll push back to the turnkey repo, but unless you've also changed the readme it shouldn't conflict (and even if it does, I can fix it easy).

**Comment by MPTMG** [comment]
Yeah problem I am working through right now is the config file from YouPHPTube live plugin for nginx fails when copied over default nginx conf. Works fine as a config file when installed from source, but when replacing the default debian install it fails to start. I will figure this one out and maybe learn something about nginx in the process.

**Comment by MPTMG** [comment]
This is ready now pull request submitted with nginx and rtmp module installed from the debian repositories. Also setup rewrite rules on port 80 to redirect all traffic not from localhost to https. It needs to be this way because the live streaming function in youphptube needs access to unencrypted youphptube site for the live counter to operate correctly.

**Comment by JedMeister** [comment]
Awesome thanks tons man. Sorry I've been so slow on this. I'm working my way back to it. This appliance looks super awesome and I really want to add it to v15.0 release.

**Comment by MPTMG** [comment]
Just built this with your changes. There appears to be an error in 20regen-youphptube-secrets, it is hanging on firstboot at that point and thus the configuration of YouPHPTube does not complete. I am working to isolate the issue and will update you when I find what the exact issue is.

**Comment by JedMeister** [comment]
@MPTMG - thanks for the heads up. I'll have a quick look myself now and post back if I can see what's up.

**Comment by MPTMG** [comment]
Sorry I isolated the issue your random generation of salt is causing system to hang. I made changes but have yet to commit them. Essentially changing your subroutine for random strong generation to 

date +%s | sha256sum | base64 | head -c 13

does the trick for me and seems sufficiently secure for the salt.

Let me know if you want me to commit my changes to my repo (it is updated to your fork) and submit a pull request. Still need to test live stream, but got tied up with another project today.

**Comment by MPTMG** [comment]
Live stream is not working nginx is failing to start:

it is looking for /usr/sbin/nginx and not finding it thus not starting. I am going to add nginx back into /plan/main to see if it is derived from the removal of nginx from plan/main and having it install via conf.d/main along with the rtmp module.

I will let you know if this fixes the issue.

**Comment by MPTMG** [comment]
nginx still failing to start.

**Comment by JedMeister** [comment]
Sorry I missed your earlier post.

I actually did some work on the inithook and resolved it a slightly different way. It turns out that `cat /dev/urandom` is bad practice anyway...

Yes, it appears that nginx does need to be in the plan (although it looks like the `nginx-light` package may be sufficient). It appeared to me that nginix was a dependency of the rmtp module, but it appears not...!

The issues with Nginx not starting appear to be a missing directory:
```
# nginx -c /etc/nginx/nginx.conf -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] mkdir() "/HLS/live" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by JedMeister** [comment]
PS, seeing as you're looking at this, rather than doubling up, I might leave you to it. If you get stuck and/or want to handball any remaining issues back to me, please let me know.

**Comment by MPTMG** [comment]
Okay I will work it tomorrow and have it working and submit a pull request.

**Comment by MPTMG** [comment]
Everything is fixed now. Tested inital boot and configuration, live stream (streaming and viewing), video link embed (creating and streaming), video upload, and video playback. Seems 100% functional 

Here are the simple fixes:
Added /HLS/live directory creation via conf.d/main 
changed the salt generation in inithooks
included nginx in plan/main.
updated database version in configuration to latest from YouPHPTube

I submitted a pull request to integrate my changes to get it ready for release.

**Comment by JedMeister** [comment]
Ok great thanks! You rock! :smile: 

I'll merge your code and do the "official" build ASAP (today hopefully, Monday at the latest) and do the final QA checks. Then it'll get published as part of the last stage of the v15.0 release (with the other 20-odd remaining appliances). 

We still have the TVHeadend appliance to go, but I'll need to discuss with my colleague about that one and see what he thinks. IIRC we were looking at using the firewall to lock it down. As that's a departure from our existing defaults (i.e. pre-enabling the firewall) I'll need to get his input on that.

Having said that, I think that we should probably have a broader discussion on enabling the firewall by default anyway (perhaps just doing it, or perhaps consider making it a firstboot option?).

**Comment by MPTMG** [comment]
My .02 is that for any appliance that is primarily focused on LAN based protocols (SMB, AFP, Anything Insecure (TVHeadend stream), etc) it is best to just enable the firewall by default and build in a VPN option for the end user. I.E. when deployed on their LAN no further config necessary, however when deployed remotely it will be inherently secure and have the option for VPN access.

I have the ZeroTierOne option ready with functional confconsole plugin for the TimeCapsule Appliance. In addition to that I have a working raccoon IPSec tunnel in the default TimeCapsule Appliance that allows for incoming remote connections. I know you talked about creating an OpenVPN option in the past as well. Naturally ZeroTier is the easiest of the options IMHO.

**Comment by MPTMG** [comment]
I synced my code with the turnkeylinux branch and there are some things that broke YouPHPTube for certain conditions. You added a rewrite rule to the yphptube.conf for YouPHPTube to redirect to the domain. This redirect/rewrite rule causes YouPHPTube to fail to load when an IP is used instead of a domain. I commented out the lines in the yphptube.conf file and the associated lines that edited this during firstboot.

I don't know if it is possible to handle both cases (domain or IP) with a rewrite rule. I understand why you made the changes as it would be perfect to always have all connections redirect to the configured domain, but inherently requires everyone to use a domain to include during testing. Didn't test by setting up domain resolution locally, but will make sure rewrite rule works for domains shortly in case you want to enforce use of a domain.

In addition to commenting out the above changes I integrated the YouPHPTubeEncoder into the appliance and configured it to listen on 81/445 so that users can host their own encoder instead of using the public encoder.

I will submit a pull request with the changes after I finish testing.

**Comment by MPTMG** [comment]
Running into similar issues with the rewrite rule when using a domain that is resolved locally. I recommend dropping the rewrite rule if there are no objections.

**Comment by MPTMG** [comment]
Rewrite rule is causing errors in released appliance.

Error in Firefox:

The page isn’t redirecting properly

An error occurred during a connection to 192.168.88.34.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

Error in Chrome:

This page isn’t working
192.168.88.34 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

As soon as rewrite rule is removed from yphptube.conf (SSL/443) section everything works just fine.

**Comment by JedMeister** [comment]
Hi @MPTMG

Apologies on slow response. And extra apologies on breaking things...

The main reason why I redirected the domain was because during my testing, if I used only the IP address, none of the CSS worked so the page looked totally broken.

In my experience, if/when users encounter that sort of behaviour, they often just assume that the TurnKey appliance is broken and move on. The odd user will inquire which gives us the opportunity to explain, but the more that we can catch before they assume our appliances are just broken, the better.

However, you raise a valid point. Setting an IP address instead of a domain, should be a valid option. To support the use of IP address we'll need to tweak the redirect. I have only done preliminary testing so far, but replacing the existing rewrite condition in the https section:
```
RewriteCond %{HTTP_HOST} ^\d+.
```
With something like this should do the trick:
```
RewriteCond %{HTTP_HOST} !^<IP_OR_DOMAIN>$
```
(where `<IP_OR_DOMAIN>` is the IP or domain updated by the inithook)

It appears to work ok for IP addresses with that modification. I'll tweak the inithook and do some more testing.

PS thanks for the heads up on this. This issue will actually affect a number of other v15.x appliances!

**Comment by JedMeister** [comment]
(removed updated comment from last post to add as a comment)

@MPTMG - you note:

> Running into similar issues with the rewrite rule when using a domain that is resolved locally.

Out of interest, how did you set that up? FWIW I simply edit my `/etc/hosts` file and it works fine for me (in both Chrome and Firefox)?!

**Comment by MPTMG** [comment]
I just setup a static dns entry on my router, so that "whateveridecide.lan" resolves to the test VM IP address and then use turnkey-init to reconfigure the domain on the VM. It really should not matter whether it is the host file or the router resolving the address. I will test again maybe there was a browser cache issue causing me to experience the error in both cases. I just assumed it was not a cache issue because as soon as I removed the rewrite condition and (service apache2 restart) it worked without issue using the domain or the IP when YPHPT was configured to use each.

I understand about the css being broken and looking for a way to resolve it. I think it is an excellent idea to ensure nobody gets turned away from TKL by thinking the appliance is broken.

**Comment by JedMeister** [comment]
I'm not sure, but perhaps the reason why you're having issues with the redirect is because of the 301 redirect (from http)? AFAIK a 301 redirect will be cached by your browser indefinitely. Perhaps we should remove the 301 redirect by default? Obviously including it is a good idea for a permanent site, but no so good for testing...

**Comment by JedMeister** [comment]
PS, seeing as we've now released this appliance I'm going to close this issue. 

Thanks again for all your great work @MPTMG (on this and other appliances). I really appreciate the input.

As you may have noticed, I've opened a new issue regarding the redirect problem (#1230) and will aim to have a proper fix ASAP (although not 100% sure when the updated/fixed app will be released).
